/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_gpufit_Gpufit */

#ifndef _Included_com_github_gpufit_Gpufit
#define _Included_com_github_gpufit_Gpufit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_gpufit_Gpufit
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_github_gpufit_Gpufit_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_gpufit_Gpufit
 * Method:    fit
 * Signature: (IILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_github_gpufit_Gpufit_fit
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_github_gpufit_Gpufit
 * Method:    getLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_gpufit_Gpufit_getLastError
  (JNIEnv *, jclass);

/*
 * Class:     com_github_gpufit_Gpufit
 * Method:    isCudaAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_gpufit_Gpufit_isCudaAvailable
  (JNIEnv *, jclass);

/*
 * Class:     com_github_gpufit_Gpufit
 * Method:    getCudaVersion
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_github_gpufit_Gpufit_getCudaVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
